version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "8090:8090"
      - "8008:8008"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/var/www/localhtml/index.html:ro
      - ./ssl/:/etc/nginx/ssl/
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
